// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZS3CBqdGw7lw1zkUtbJSSzAKyma03aH0',
    appId: '1:338147433997:web:9283311fe8c0d6f8ebbf44',
    messagingSenderId: '338147433997',
    projectId: 'advert-4b9e6',
    authDomain: 'advert-4b9e6.firebaseapp.com',
    storageBucket: 'advert-4b9e6.appspot.com',
    measurementId: 'G-Q7WTF24YTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiatYAPs1HG5Oidb0QGxg-EWD_-bTcr74',
    appId: '1:338147433997:android:df74dd98c907da09ebbf44',
    messagingSenderId: '338147433997',
    projectId: 'advert-4b9e6',
    storageBucket: 'advert-4b9e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuSCO1g8xnvAQ6IWMBcF4MouV6Qyv9A_I',
    appId: '1:338147433997:ios:aec623315ee5d72cebbf44',
    messagingSenderId: '338147433997',
    projectId: 'advert-4b9e6',
    storageBucket: 'advert-4b9e6.appspot.com',
    iosClientId: '338147433997-tr5pj1dk2eek3ve4465pkelss7sarfh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.advert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuSCO1g8xnvAQ6IWMBcF4MouV6Qyv9A_I',
    appId: '1:338147433997:ios:b8569ac2da2d5ee3ebbf44',
    messagingSenderId: '338147433997',
    projectId: 'advert-4b9e6',
    storageBucket: 'advert-4b9e6.appspot.com',
    iosClientId: '338147433997-s5s7v9ukf2plkk8e9l4jir2ikrlp8qk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.advert.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZS3CBqdGw7lw1zkUtbJSSzAKyma03aH0',
    appId: '1:338147433997:web:66a2041907e2ede7ebbf44',
    messagingSenderId: '338147433997',
    projectId: 'advert-4b9e6',
    authDomain: 'advert-4b9e6.firebaseapp.com',
    storageBucket: 'advert-4b9e6.appspot.com',
    measurementId: 'G-DG5JJ30T66',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDZS3CBqdGw7lw1zkUtbJSSzAKyma03aH0',
    appId: '1:338147433997:web:a1aa60a773ede979ebbf44',
    messagingSenderId: '338147433997',
    projectId: 'advert-4b9e6',
    authDomain: 'advert-4b9e6.firebaseapp.com',
    storageBucket: 'advert-4b9e6.appspot.com',
    measurementId: 'G-ELY7L953BK',
  );
}
